version: '3.3'
services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend: 
    container_name: foodgram-back
    image: wowlass/foodgram_backend
    volumes:
      - static_volume:/app/static/
      - media:/app/media/
    env_file: .env
    depends_on: 
      - postgres
  frontend:
    container_name: foodgram-front
    image: wowlass/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  infra:
    container_name: foodgram-proxy
    image: wowlass/foodgram_infra
    depends_on:
      - backend
      - frontend
    ports:
      - "8000:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/app/static/
      - media:/app/media/
volumes:
  pg_data:
  static_volume:
  media: