# Generated by Django 4.2 on 2025-03-21 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_rename_unit_ingridients_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridients',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('мл', 'миллилитр'), ('л', 'литр'), ('шт', 'штука')], max_length=15, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False, verbose_name='В списке покупок'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название тэга'),
        ),
    ]
