# Generated by Django 4.2 on 2025-03-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingridients_measurement_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes', verbose_name='Рецеп в списке покупок')),
            ],
            options={
                'verbose_name': 'Список покупок для рецептов',
                'verbose_name_plural': 'Списки покупок для рецептов',
            },
        ),
    ]
