# Generated by Django 4.2 on 2025-03-23 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_favoritsrecipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritsrecipes',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes', verbose_name='Рецепты'),
        ),
        migrations.AlterField(
            model_name='favoritsrecipes',
            name='user',
            field=models.ForeignKey(help_text='У какого пользователя рецепт в избраном', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='shoppingcard',
            name='recipes',
            field=models.ForeignKey(help_text='Какой рецепт надо добавить в список', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='shoppingcard',
            name='user',
            field=models.ForeignKey(help_text='Какому пользователю добавить рецепт в список покупок', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
