# Generated by Django 4.2 on 2025-03-24 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_favoritsrecipes_recipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritsrecipes',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipes', verbose_name='Рецепты'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='recipes.ingridients', verbose_name='Список ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='recipes.tag', verbose_name='Список id тегов'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='text',
            field=models.TextField(max_length=650, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shoppingcard',
            name='recipes',
            field=models.ForeignKey(help_text='Какой рецепт надо добавить в список', on_delete=django.db.models.deletion.CASCADE, related_name='recipes_in_card', to='recipes.recipes', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Уникальный слаг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Уникальное название'),
        ),
    ]
