# Generated by Django 4.2 on 2025-03-31 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_title_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingridients',
            old_name='title',
            new_name='name',
        ),
    ]
