# Generated by Django 4.2 on 2025-03-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatars', verbose_name='Аватар пользователя'),
            preserve_default=False,
        ),
    ]
