# Generated by Django 4.2 on 2025-03-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_is_subscribed_alter_myuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='/frontend/build/static/media/userpic-icon.2e3faa821bb5398be2c6.jpg', upload_to='avatars', verbose_name='Ссылка на аватар'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_subscribed',
            field=models.BooleanField(verbose_name='Подписан ли текущий пользователь на этого'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Уникальный юзернейм'),
        ),
    ]
