# Generated by Django 4.2 on 2025-04-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_follow_remove_myuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
