# Generated by Django 4.2 on 2025-04-11 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_follow_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='avarat',
            new_name='avartar',
        ),
    ]
