# Generated by Django 4.2 on 2025-04-11 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_avarat_myuser_avartar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='avartar',
            new_name='avatar',
        ),
    ]
